---
title: "Fig 5"
output: html_notebook
---

```{r setup}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```


```{r}
library("tidyverse")
library("ggplot2")
```


```{r}

ggplot_scientific_notation_axes_labels <- function(l) {
  # 'prettyNum' puts things into scientific notation when digit strings get past a certain length,
  # but keeps things  >0.0001 and < 10^7 in non-sci notation
  l <- prettyNum(l)
  # … but for axis labels, we want to switch to powers of 10 for anything >=10^3 or < 0.01
  # (though you decide)
  for(i in 1:length(l)){
    number=eval(parse(text=l)[i])
    if(!is.na(number) & (number<0.001 | number>=1000)) l[i]=format(number, scientific=TRUE)
  }
  # quote the part before the exponent to keep all the digits
  l <- gsub("^(.*)e", "'\\1'e", l)
  # remove + after exponent, if exists. E.g.: (e^+2 -> e^2)
  l <- gsub("e\\+","e",l)  
  l <- gsub("e0","e",l)  
  l <- gsub("e-0","e-",l) 
  # turn the 'e' into plotmath format
  l <- gsub("e", "%*%10^", l)
  # convert 1x10^ or 1.000x10^ -> 10^
  l <- gsub("\\'1[\\.0]*\\'\\%\\*\\%", "", l)
  # convert 0.000.. * 10^x to 0
  l <- gsub("\\'0[\\.0]*\\'\\%\\*\\%", "", l)
  l <- gsub("10\\^0", "0", l)
  # return this as an expression
  parse(text=l)
}


# x axis major tick marks - corresponding to time post START treatment
major.ticks.actual.times=c(7,10,15, 25,35,45,55,65, 75) 
major.ticks.time.post.tx=as.character(major.ticks.actual.times-5)
# Option to put some gaps in this label list to stop numbers overlapping
#shifted.time.labels[shifted.time.labels=="50"] = ""
#shifted.time.labels[shifted.time.labels=="70"] = ""
# minor breaks
mb=c(6:75)

plotwidth=12
golden.ratio=1.618
smaller.font.size=19
larger.font.size=21
legend.font.size=11
panel.label.size = 24
point_line_size = 1

plotwidth=12
smaller.font.size=16
larger.font.size=18
panel.label.size = 22


```

```{r}
load("../data/DataObjects/final_data_flow_model_v2.RData")
```

```{r}
frac_Ki67 <- map_depth(final_data_flow_model_v2,2, ~do.call(rbind,.))
frac_Ki67 <- map(frac_Ki67, ~c(.$Ki67_YFP_frac["norm_frac_Ki67_YFP"], .$Ki67_frac) %>% 
                   data.frame(.) %>%
                   pivot_longer(data = ., cols = 1:2, names_to = "label", values_to = "frac") %>% 
                   filter(., time >5))

frac_Ki67 <- do.call(rbind,frac_Ki67)

```


```{r}

#colors <- c("YFP+ naive" = "#F4D03F", "Total naive"= "grey20")
colors <- c("YFP+ naive" = "darkgoldenrod2", "Total naive"= "grey20")


YFP_plots_frac <- function(data, title){
  ggplot(data.frame(data), aes(x = time))+
  geom_point(aes(y = frac, color = Population, shape = Population), size = 4, alpha=0.6)+
  facet_wrap(~celltype)+
  scale_color_manual(values = colors)+
  labs(y = bquote(bold('Fraction Ki67')^bold('+')), 
       x = "Time since end of tamoxifen treatment (days)")+
    theme_bw()+ 
    theme(axis.text=element_text(size=smaller.font.size), 
          axis.title.x=element_text(size=larger.font.size, margin = margin(t = 15, r = 0, b = 0, l = 0)),
          axis.title.y=element_text(size=larger.font.size,face="bold"),
          plot.title = element_text(hjust = 0.5),
          text = element_text(family = "Helvetica", size = larger.font.size),
          legend.position = c(0.35, 0.8),
          legend.title =element_text(size=smaller.font.size, face="bold"),
          legend.text=element_text(size=smaller.font.size),
          legend.key = element_rect(fill = "transparent"),
          #legend.key.height = unit(10),
          #legend.direction= "vertical",
          strip.background = element_rect(color = "black", fill = "#FBFCFC"),
          strip.text = element_text(face = "bold",size = larger.font.size))+
    scale_x_log10(limits=c(7,75), breaks=major.ticks.actual.times, minor_breaks = mb, labels=major.ticks.time.post.tx)+
    scale_y_log10(minor_breaks=NULL, labels = ggplot_scientific_notation_axes_labels)+
    coord_cartesian(xlim=c(7,65)) # trims the x-axis
}

frac_Ki67$celltype=droplevels(as.factor(frac_Ki67$celltype))
levels(frac_Ki67$celltype)=c("CD4", "CD8")


frac_Ki67$label=droplevels(as.factor(frac_Ki67$label))
levels(frac_Ki67$label)=c("Total naive", "YFP+ naive")
names(frac_Ki67) = c( "time",  "celltype",  "Population",   "frac")

YFP_nai_plot_frac <- YFP_plots_frac(frac_Ki67, "Periphery")

pdf("../figures/fig_6.pdf", width=plotwidth, height=plotwidth*0.5)
print(YFP_nai_plot_frac)
dev.off()


pdf("../../Manuscript/PaperFigures/Figure-6.pdf", width=plotwidth, height=0.5*plotwidth)
print(YFP_nai_plot_frac)
dev.off()
```


