---
title: "Simple model (no Ki67, fixed thymic functions)"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./html-output"
    )
  })
---

```{r setup}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

```

```{r}
packages <- c("tidyverse", "ggplot2", "cowplot") 
tmp=lapply(packages, require, character.only = TRUE)
source("grind.R")
nboots=500  # bootstrap replicates 
```

1. Simple model fitting for YFP fractions (eqn 2 in text)

```{r}
load(file = "parameters/p_Z_mSP.RData")  # parameters generated by the fitting in Y(t)_Z(t).R
```


```{r}
nai_model_Z <- function(receptor){ 
  p_tmp <- p_Z_mSP[[receptor]]
  model_Z <- function(t, state, parms) {
  with(as.list(c(state,parms)), {
    Z = Z0*exp(a*t)/(1+exp(v*(t-tau)))^((a+b)/v)
    return(Z) 
  }) 
}
  function(t, state, parms) {
    with(as.list(c(state,parms)), {
      dN = theta*model_Z(t, NULL,p_tmp)  - mu*N
      return(list(c(dN)))
    })
  }

}
```

```{r}
fun_logit <- function (x){
  x[x<0] <- 0
  #print(x)
  return(log(x/(1-x)))
}

fun_log <- function (x){ 
  x[x<0] <- 0
  return(log(x))
}


```

```{r}
load(file = "../data/DataObjects/final_data_simple_model.RData")  # all the data for the simple model (all of Thea's data, organised, minus any Ki67 info)
```

```{r}

# YFP_frac is a list (CD4, CD8) of time vs. observed YFP+ naive cell numbers, with ID

YFP_frac <- map(final_data_simple_model, ~.[["YFP_frac"]])
test <- map(YFP_frac, ~do.call(rbind,.))
test <- map2(test, names(test), ~ mutate(.x, ID = .y))
test <- do.call(rbind, test)
YFP_frac <- test %>% group_by(celltype) %>% group_split()
names(YFP_frac ) <- c("CD4", "CD8")

# strip it of ID and other stuff for fitting:
YFP_frac_fitting <- map(YFP_frac, ~ mutate(., time = time - 4) %>% 
                          mutate(., N = norm_frac_YFP)%>%
                          filter(., !is.na(N))%>%
                          filter(., time < 80) %>% 
                          select(., c("time", "N")))

```

Make the fits

```{r}
Z_fit <- map2(YFP_frac_fitting, names(YFP_frac_fitting),~
    
    fit(data.frame(.x),
        odes = nai_model_Z(.y),
        free = c("theta", "mu", "N"),
        state = c( "N" = 0.001),
        parms = c( theta = 0.6, mu = 0.03),
        upper = c(3, 1, 0.5),
        lower = c(0.0001, 0.001, 0.0001),
        fun = fun_log,
        tmax = 100,
        bootstrap = nboots,
        #bootstrap.residuals = TRUE,
       method="Pseudo"
       )
)

simple_frac <- Z_fit 
save(simple_frac, file = "DataObjects/simple_frac.RData")

```

 store fits in frac_table

```{r}

frac_parms <- map(simple_frac,   ~.[["par"]][c("theta","mu")])
frac_state <- map(simple_frac,  ~.[["par"]]["N"]) 

frac_table <- map(c("CD4" = "CD4", "CD8" = "CD8"), ~ run(tmax = 100, tstep=0.1,
                                          state =frac_state[[.]],
                                          parms = frac_parms[[.]],
                                          odes = nai_model_Z(.),
                                          table = TRUE))

frac_table <- map(frac_table, ~mutate(., time = time+4))
```

Generate an integrated table of the simple_frac fit and observations, with Mouse IDs, and save it 

```{r} 

# load("../data/ID_mouseID.Rdata")
# ID_mouseID <- ID_mouseID[[1]]
# colnames(ID_mouseID) <- c("ID", "MouseID")
# YFP_frac <- map(YFP_frac, ~merge(., ID_mouseID, by = "ID"))

frac_table_data <- map2(frac_table,
                                 YFP_frac, ~ 
                                   merge(.x, .y, by = "time", all = T))#%>%  map(~rename(.,data = N.y, model = N.x))

#%>%  map(~mutate(., residuals = fun_logit(model) - fun_logit(data)))

frac_YFP_nai <- rbind(cbind(frac_table_data[[1]],  "cell" = rep("CD4", nrow(frac_table_data[[1]]))),
                    cbind(frac_table_data[[2]],   "cell" = rep("CD8", nrow(frac_table_data[[2]]))))

simple_frac_table <- frac_YFP_nai %>% select(-celltype) %>% rename(celltype=cell, model=N, data= norm_frac_YFP)

write_rds(simple_frac_table, file = "../scripts_figures/simple_frac_table.Rds")

```

2. Simple model fitting for cell counts of YFP expressing naive T cells (eqn 1)

```{r}
load(file = "parameters/p_YFP_mSP.RData")
```

```{r} 
#for keeping IDs 
YFP_abs <- map(final_data_simple_model, ~.[["cell_numbers_YFPpos"]])
test <- map(YFP_abs, ~do.call(rbind,.))
test <- map2(test, names(test), ~ mutate(.x, ID = .y))
test <- do.call(rbind, test)
YFP_abs <- test %>% group_by(celltype) %>% group_split()
names(YFP_abs ) <- c("CD4", "CD8")

YFP_abs_fitting <- map(YFP_abs, ~ mutate(., time = time - 4) %>% 
                          mutate(., N = cell_number_tot)%>%
                          filter(., time < 80) %>% 
                          select(., c("time", "N")))

YFP_abs <- map(YFP_abs, ~ mutate(., N = cell_number_tot))
```

Fit on absolute YFP+ counts

```{r}

# function defining input of YFP+ numbers from thymus - taken from "Fitting A"
nai_model_abs<- function(receptor){ 
  p_tmp <- p_YFP_mSP[[receptor]]
  mSP_model <- function(t, state, parms) {
  with(as.list(c(state,parms)), {
    Y = Y0 + (a*t^b) * exp(-c*t)
    return(Y) 
  }) 
}

  function(t, state, parms) {
    with(as.list(c(state,parms)), {
      dN = theta*mSP_model(t, NULL,p_tmp) - mu*N 
      return(list(c(dN)))
    })
  }

}

p  <- list("CD4" = c("theta" = 0.5, "mu" = 1/4), 
           "CD8" =  c("theta" = 0.5, "mu" = 1/30))

lower  <- list("CD4" = c("theta" = 0.01, "mu" = 1/100, "N" = 1), 
           "CD8" =  c("theta" = 0.1, "mu" = 1/100, "N" =  1))

upper  <- list("CD4" = c("theta" = 1, "mu" = 1, "N" =  100000), 
           "CD8" =  c("theta" = 1.5, "mu" = 1, "N" =  100000))

abs_fit <- map2(YFP_abs_fitting, 
                names(YFP_abs_fitting),~
                  fit(data.frame(.x),
                      odes = nai_model_abs(.y),
                      free = c("theta","mu", "N"),
                      upper = upper[[.y]],
                      state = c(N = 2000),
                      parms = p[[.y]],
                      lower = lower[[.y]],
                      fun = fun_log,
                      bootstrap = nboots,
                      #bootstrap.residuals = TRUE,
                      method="Pseudo")
)

simple_abs <- abs_fit
save(simple_abs, file = "DataObjects/simple_abs.RData")
```

```{r}
abs_parms<- map(abs_fit, ~.$par[c("theta", "mu")])
abs_state <- map(abs_fit, ~.$par[c("N")])

abs_table <- map(names(abs_parms), ~ run(tmax = 100, tstep=0.1,
                                         state =abs_state[[.]],
                                         parms = abs_parms[[.]],
                                         odes = nai_model_abs(.),
                                         table = TRUE))

abs_table<- map(abs_table, ~mutate(., time = time+4))

abs_table_data <- map2(abs_table, YFP_abs, ~
                         merge(.x, .y, by = "time", all = TRUE)) %>% 
  map(~rename(., model = N.x, data = N.y))

#abs_table_data<- map(abs_table_data, ~mutate(., residuals = log(model)-log(data)))

abs_table_data <- rbind(cbind(abs_table_data[[1]],  "cell" = rep("CD4", nrow(abs_table_data[[1]]))),
                    cbind(abs_table_data[[2]],   "cell" = rep("CD8", nrow(abs_table_data[[2]]))))

simple_abs_table <- abs_table_data %>% select(-celltype) %>% select(-cell_number_tot) %>% rename(celltype=cell)

write_rds(simple_abs_table, file = "../scripts_figures/simple_abs_table.Rds")
```

Save all parameters

```{r}
frac_total <- map2(frac_parms, frac_state, ~ c(.x,.y))
abs_total <- map2(abs_parms, abs_state, ~ c(.x,.y))

all <- map2(frac_total, abs_total, ~ rbind(.x,.y)) %>% 
  map(~{row.names(.) = c("Fraction", "Absolute");.}) %>%
  map(~data.frame(.))

#all <- make_long(all)
write.csv(all, file = "parameters/simple_model_parameters.csv")
```



```{r}
save.image("DataObjects/simple_model.RData")
```





